[[pages]]
path = "pages/Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Data_Science_Projects.py"
name = "Data Science Projects"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Work_Experience.py"
name = "Work Experience"
icon = "ğŸ’¼"

[[pages]]
path = "pages/Banking_Dynamics.py"
name = "Banking Dynamics"
icon = "ğŸ¦"

[[pages]]
path = "pages/MH_DisClass.py"
name = "Mental Health Discourse Classifier"
icon = "ğŸ§ "